### ISSUE TITLE
Random port is used.

### ISSUE THREAD

**Issue by 0rangeFox** [MichaelMarner/dart-redux-remote-devtools#37] opened 2021-08-11 15:01 UTC
Hey guys, before I create this issue, yes I have already explored and I am aware that this is duplicated from issue #36, but anyway I decided to create another one, apparently it is already stopped, so the problem is this, I have already made the modifications on my current project and apparently it doesn't seem to work, so I decided to use your examples and still I have the same problem, I am available to debug or log whatever.

I also checked to see if there were any of these errors in the [SocketCluster Dart Client](https://github.com/pauldemarco/socketcluster_client) library, and still no solution. Then later I noticed that it uses a different connection URL, and even then I tested it, and it seems to only recognize "ws" as the IP.

Any more information that is needed to clarify I am here. Any help or attempts are welcome and I appreciate it.

**Comment by MichaelMarner** [comment] 2021-08-12 00:40
Hi @0rangeFox thanks for this, but I'm going to close this ticket and direct you to #36, since it's the same issue. Please have a read of my explanation there, what you are seeing is not a bug in this library.

Please feel free to reopen if you think you have a different problem.

**Closed as completed by MichaelMarner** 2021-08-12 00:40 UTC
Labels: duplicate
